const $=s=>document.querySelector(s);
const text=$('#qrText'),generate=$('#generateButton'),result=$('#resultBox'),output=$('#qrOutput'),download=$('#downloadButton'),status=$('#status');
const translations={
en:{allTools:'All tools',privacy:'Privacy',eyebrow:'Utility tool',title:'QR Code Generator',subtitle:'Turn a link or text into a downloadable QR code.',caption:'Enter content · create QR · download PNG',contentLabel:'QR content',contentHint:'Link or text',sizeLabel:'Image size',marginLabel:'Margin',localTitle:'Processed on your device',localCopy:'Your content is never uploaded to a server.',generate:'Create QR code',download:'Download PNG',why:'Why ConvertFiles24',featureTitle:'Simple and private QR creation',privateTitle:'Private by design',privateCopy:'Everything stays in your browser.',fastTitle:'Ready in seconds',fastCopy:'Create a clean QR code with one click.',downloadTitle:'High-quality PNG',downloadCopy:'Choose a size suitable for screen or print.',copyright:'© 2026 ConvertFiles24. Safe local tools.',privacyPolicy:'Privacy Policy',terms:'Terms',ready:'QR code is ready.',empty:'Enter a link or text first.',failed:'Could not create the QR code.'},
ko:{allTools:'모든 도구',privacy:'개인정보 보호',eyebrow:'편의 도구',title:'QR 코드 만들기',subtitle:'링크나 문자를 다운로드 가능한 QR 코드로 만드세요.',caption:'내용 입력 · QR 생성 · PNG 다운로드',contentLabel:'QR 내용',contentHint:'링크 또는 문자',sizeLabel:'이미지 크기',marginLabel:'여백',localTitle:'기기에서 안전하게 처리',localCopy:'입력 내용은 서버로 전송되지 않습니다.',generate:'QR 코드 만들기',download:'PNG 다운로드',why:'CONVERTFILES24를 선택하는 이유',featureTitle:'간단하고 안전한 QR 생성',privateTitle:'개인정보 보호 설계',privateCopy:'모든 작업은 브라우저 안에서 처리됩니다.',fastTitle:'몇 초 만에 완성',fastCopy:'한 번의 클릭으로 선명한 QR 코드를 만듭니다.',downloadTitle:'고화질 PNG',downloadCopy:'화면이나 인쇄에 맞는 크기를 선택하세요.',copyright:'© 2026 ConvertFiles24. 안전한 기기 내 도구.',privacyPolicy:'개인정보처리방침',terms:'이용약관',ready:'QR 코드가 준비되었습니다.',empty:'링크나 문자를 먼저 입력하세요.',failed:'QR 코드를 만들지 못했습니다.'},
ja:{allTools:'すべてのツール',privacy:'プライバシー',eyebrow:'便利ツール',title:'QRコード作成',subtitle:'リンクや文字をダウンロード可能なQRコードにします。',caption:'内容入力 · QR作成 · PNG保存',contentLabel:'QRの内容',contentHint:'リンクまたは文字',sizeLabel:'画像サイズ',marginLabel:'余白',localTitle:'端末内で安全に処理',localCopy:'入力内容はサーバーへ送信されません。',generate:'QRコードを作成',download:'PNGをダウンロード',why:'ConvertFiles24を選ぶ理由',featureTitle:'簡単で安全なQR作成',privateTitle:'プライバシー設計',privateCopy:'すべてブラウザ内で処理します。',fastTitle:'数秒で完成',fastCopy:'ワンクリックでQRコードを作成します。',downloadTitle:'高品質PNG',downloadCopy:'画面や印刷に適したサイズを選べます。',copyright:'© 2026 ConvertFiles24.',privacyPolicy:'プライバシーポリシー',terms:'利用規約',ready:'QRコードが完成しました。',empty:'リンクまたは文字を入力してください。',failed:'QRコードを作成できませんでした。'},
es:{allTools:'Todas las herramientas',privacy:'Privacidad',eyebrow:'Herramienta útil',title:'Generador de códigos QR',subtitle:'Convierte un enlace o texto en un código QR descargable.',caption:'Escribe · crea QR · descarga PNG',contentLabel:'Contenido QR',contentHint:'Enlace o texto',sizeLabel:'Tamaño de imagen',marginLabel:'Margen',localTitle:'Procesado en tu dispositivo',localCopy:'El contenido no se envía al servidor.',generate:'Crear código QR',download:'Descargar PNG',why:'Por qué elegir ConvertFiles24',featureTitle:'Creación QR sencilla y privada',privateTitle:'Privacidad por diseño',privateCopy:'Todo se procesa en el navegador.',fastTitle:'Listo en segundos',fastCopy:'Crea un código QR con un clic.',downloadTitle:'PNG de alta calidad',downloadCopy:'Elige un tamaño para pantalla o impresión.',copyright:'© 2026 ConvertFiles24.',privacyPolicy:'Política de privacidad',terms:'Términos',ready:'El código QR está listo.',empty:'Escribe primero un enlace o texto.',failed:'No se pudo crear el código QR.'}};
let lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('convertfiles24-language')||'en';if(!translations[lang])lang='en';const tr=k=>translations[lang][k]||translations.en[k]||k;
function applyLanguage(){document.documentElement.lang=lang;$('#languageSelect').value=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));}
text.addEventListener('input',()=>{$('#charCount').textContent=text.value.length;generate.disabled=!text.value.trim();result.hidden=true;status.textContent='';});
generate.addEventListener('click',()=>{const value=text.value.trim();if(!value){status.textContent=tr('empty');status.className='status error';return;}try{output.innerHTML='';const size=Number($('#sizeSelect').value),margin=Number($('#marginSelect').value),pad=Math.round(size*margin/50),qrSize=size-pad*2;new QRCode(output,{text:value,width:qrSize,height:qrSize,colorDark:'#111111',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H});setTimeout(()=>{const source=output.querySelector('canvas');if(!source)throw new Error('No QR image');const canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);ctx.drawImage(source,pad,pad,qrSize,qrSize);output.innerHTML='';output.append(canvas);const url=canvas.toDataURL('image/png');download.href=url;download.download='qrcode.png';result.hidden=false;status.textContent=tr('ready');status.className='status';},40);}catch(e){console.error(e);status.textContent=tr('failed');status.className='status error';}});
$('#languageSelect').addEventListener('change',e=>{lang=e.target.value;localStorage.setItem('convertfiles24-language',lang);const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState({},'',u);applyLanguage();});
$('#themeButton').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('convertfiles24-theme',theme);$('#themeIcon').textContent=theme==='dark'?'dark_mode':'light_mode';});$('#themeIcon').textContent=document.documentElement.dataset.theme==='dark'?'dark_mode':'light_mode';applyLanguage();
