(()=>{"use strict";
const $=s=>document.querySelector(s),ui={input:$("#fileInput"),drop:$("#dropZone"),selected:$("#selectedFile"),name:$("#fileName"),meta:$("#fileMeta"),replace:$("#replaceButton"),divider:$("#settingsDivider"),settings:$("#splitSettings"),rangeField:$("#rangeField"),range:$("#rangeInput"),rangeHelp:$("#rangeHelp"),split:$("#splitButton"),status:$("#status"),download:$("#downloadButton"),downloadLabel:$("#downloadLabel"),language:$("#languageSelect"),theme:$("#themeButton"),themeIcon:$("#themeIcon")};
const copy={
en:{allTools:"All tools",privacy:"Privacy",eyebrow:"PDF tools",title:"Split PDF",subtitle:"Separate PDF pages or extract only the pages you need.",formatCaption:"Split every page or extract a page range",selectLabel:"Select PDF",dropTitle:"Choose a PDF to split",dropCopy:"Select one PDF or drag it here",choose:"Choose PDF",limit:"1 file · up to 50MB",replace:"Other PDF",splitMethod:"Split method",allPages:"Every page",rangePages:"Page range",rangeLabel:"Pages to extract",rangeHelp:"Example: 1-3, 5",localTitle:"Processed on your device",localCopy:"The PDF is never uploaded to a server.",split:"Split PDF",downloadZip:"Download split pages (ZIP)",downloadPdf:"Download extracted PDF",processing:"Splitting PDF on your device…",readyZip:"Split pages are ready",readyPdf:"Extracted PDF is ready",badType:"Choose a PDF file.",tooLarge:"Choose a PDF no larger than 50MB.",invalidPdf:"This PDF could not be opened.",invalidRange:"Enter valid pages within this PDF.",failed:"This PDF could not be split.",pages:n=>`${n} pages`,why:"Why ConvertFiles24",featureTitle:"Simple and secure PDF splitting",privateTitle:"Private by design",privateCopy:"Your PDF stays on your device while it is processed.",choiceTitle:"Split your way",choiceCopy:"Separate every page or extract a custom range.",worksTitle:"Works everywhere",worksCopy:"Use it in your desktop, tablet or mobile browser.",copyright:"© 2026 ConvertFiles24. Client-side excellence.",privacyPolicy:"Privacy Policy",terms:"Terms of Service"},
ko:{allTools:"모든 도구",privacy:"개인정보 보호",eyebrow:"PDF 도구",title:"PDF 나누기",subtitle:"PDF 페이지를 각각 나누거나 필요한 페이지만 추출하세요.",formatCaption:"모든 페이지 나누기 또는 페이지 범위 추출",selectLabel:"PDF 선택",dropTitle:"나눌 PDF 파일을 선택하세요",dropCopy:"PDF 한 개를 선택하거나 여기로 끌어오세요",choose:"PDF 선택",limit:"파일 1개 · 최대 50MB",replace:"다른 PDF",splitMethod:"나누기 방식",allPages:"모든 페이지",rangePages:"페이지 범위",rangeLabel:"추출할 페이지",rangeHelp:"예: 1-3, 5",localTitle:"기기에서 안전하게 처리",localCopy:"PDF 파일은 서버로 업로드되지 않습니다.",split:"PDF 나누기",downloadZip:"나눈 페이지 다운로드 (ZIP)",downloadPdf:"추출한 PDF 다운로드",processing:"기기에서 PDF 나누는 중…",readyZip:"나눈 페이지가 준비되었습니다",readyPdf:"추출한 PDF가 준비되었습니다",badType:"PDF 파일을 선택하세요.",tooLarge:"50MB 이하의 PDF를 선택하세요.",invalidPdf:"이 PDF 파일을 열 수 없습니다.",invalidRange:"PDF 범위 안의 올바른 페이지를 입력하세요.",failed:"PDF 파일을 나누지 못했습니다.",pages:n=>`${n}페이지`,why:"ConvertFiles24를 선택하는 이유",featureTitle:"간단하고 안전한 PDF 나누기",privateTitle:"개인정보 보호 설계",privateCopy:"PDF는 기기 밖으로 전송되지 않고 안전하게 처리됩니다.",choiceTitle:"원하는 방식으로 나누기",choiceCopy:"모든 페이지를 나누거나 필요한 범위만 추출할 수 있습니다.",worksTitle:"모든 기기에서 사용",worksCopy:"PC, 태블릿, 스마트폰 브라우저에서 바로 사용할 수 있습니다.",copyright:"© 2026 ConvertFiles24. 안전한 기기 내 파일 처리.",privacyPolicy:"개인정보처리방침",terms:"이용약관"},
ja:{allTools:"すべてのツール",privacy:"プライバシー",eyebrow:"PDFツール",title:"PDFを分割",subtitle:"PDFをページごとに分割したり、必要なページだけを抽出します。",formatCaption:"全ページを分割またはページ範囲を抽出",selectLabel:"PDFを選択",dropTitle:"分割するPDFを選択してください",dropCopy:"PDFを1つ選択するか、ここにドロップしてください",choose:"PDFを選択",limit:"1ファイル · 最大50MB",replace:"別のPDF",splitMethod:"分割方法",allPages:"全ページ",rangePages:"ページ範囲",rangeLabel:"抽出するページ",rangeHelp:"例: 1-3, 5",localTitle:"端末内で安全に処理",localCopy:"PDFがサーバーにアップロードされることはありません。",split:"PDFを分割",downloadZip:"分割ページをダウンロード (ZIP)",downloadPdf:"抽出したPDFをダウンロード",processing:"端末内でPDFを分割中…",readyZip:"分割ページの準備ができました",readyPdf:"抽出したPDFの準備ができました",badType:"PDFファイルを選択してください。",tooLarge:"50MB以下のPDFを選択してください。",invalidPdf:"このPDFを開けません。",invalidRange:"PDF内の有効なページを入力してください。",failed:"PDFを分割できませんでした。",pages:n=>`${n}ページ`,why:"ConvertFiles24が選ばれる理由",featureTitle:"シンプルで安全なPDF分割",privateTitle:"プライバシーを重視",privateCopy:"PDFは端末の外に送信されません。",choiceTitle:"希望の方法で分割",choiceCopy:"全ページまたは必要な範囲だけを抽出できます。",worksTitle:"あらゆる端末で利用可能",worksCopy:"PC、タブレット、スマートフォンで利用できます。",copyright:"© 2026 ConvertFiles24. 安全なローカルファイルツール。",privacyPolicy:"プライバシーポリシー",terms:"利用規約"},
es:{allTools:"Todas las herramientas",privacy:"Privacidad",eyebrow:"Herramientas PDF",title:"Dividir PDF",subtitle:"Separa las páginas de un PDF o extrae solo las que necesites.",formatCaption:"Divide todas las páginas o extrae un rango",selectLabel:"Seleccionar PDF",dropTitle:"Elige el PDF que quieres dividir",dropCopy:"Selecciona un PDF o arrástralo aquí",choose:"Elegir PDF",limit:"1 archivo · máximo 50 MB",replace:"Otro PDF",splitMethod:"Método",allPages:"Cada página",rangePages:"Rango",rangeLabel:"Páginas para extraer",rangeHelp:"Ejemplo: 1-3, 5",localTitle:"Procesamiento seguro en tu dispositivo",localCopy:"El PDF nunca se sube a un servidor.",split:"Dividir PDF",downloadZip:"Descargar páginas (ZIP)",downloadPdf:"Descargar PDF extraído",processing:"Dividiendo PDF en tu dispositivo…",readyZip:"Las páginas están listas",readyPdf:"El PDF extraído está listo",badType:"Elige un archivo PDF.",tooLarge:"Elige un PDF de 50 MB o menos.",invalidPdf:"No se pudo abrir este PDF.",invalidRange:"Introduce páginas válidas del PDF.",failed:"No se pudo dividir este PDF.",pages:n=>`${n} páginas`,why:"Por qué elegir ConvertFiles24",featureTitle:"División de PDF simple y segura",privateTitle:"Privacidad desde el diseño",privateCopy:"El PDF permanece en tu dispositivo.",choiceTitle:"Divide a tu manera",choiceCopy:"Separa cada página o extrae un rango personalizado.",worksTitle:"Funciona en todos tus dispositivos",worksCopy:"Úsalo en el navegador del ordenador, tableta o móvil.",copyright:"© 2026 ConvertFiles24. Herramientas locales y privadas.",privacyPolicy:"Política de privacidad",terms:"Términos de servicio"}};
const supported=["en","ko","ja","es"];let lang=(()=>{const q=new URLSearchParams(location.search).get("lang");if(supported.includes(q))return q;try{const saved=localStorage.getItem("convertfiles24-language");if(supported.includes(saved))return saved}catch(_){}const browser=(navigator.language||"en").slice(0,2);return supported.includes(browser)?browser:"en"})(),file=null,pageCount=0,resultUrl="",resultSize=0,resultKind="zip";
function formatBytes(bytes){if(!bytes)return"0 B";const units=["B","KB","MB","GB"],i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return`${(bytes/1024**i).toFixed(i?1:0)} ${units[i]}`}
function method(){return document.querySelector('input[name="method"]:checked').value}
function renderTheme(){ui.themeIcon.textContent=document.documentElement.dataset.theme==="dark"?"☾":"☀"}
function renderLanguage(){document.documentElement.lang=lang;ui.language.value=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=copy[lang][el.dataset.i18n];if(typeof value==="string")el.textContent=value});if(file)ui.meta.textContent=`${copy[lang].pages(pageCount)} · ${formatBytes(file.size)}`;if(resultUrl){ui.downloadLabel.textContent=resultKind==="zip"?copy[lang].downloadZip:copy[lang].downloadPdf;ui.status.textContent=`${resultKind==="zip"?copy[lang].readyZip:copy[lang].readyPdf} · ${formatBytes(resultSize)}`}}
function clearResult(){if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl="";resultSize=0;ui.download.hidden=true;ui.download.removeAttribute("href");ui.status.textContent="";ui.status.className="status";ui.split.classList.remove("completed")}
function showError(message){ui.status.textContent=message;ui.status.className="status error"}
async function setFile(candidate){clearResult();if(!candidate)return;if(candidate.type!=="application/pdf"&&!candidate.name.toLowerCase().endsWith(".pdf")){showError(copy[lang].badType);return}if(candidate.size>50*1024*1024){showError(copy[lang].tooLarge);return}try{const document=await PDFLib.PDFDocument.load(await candidate.arrayBuffer(),{ignoreEncryption:true});file=candidate;pageCount=document.getPageCount();ui.name.textContent=file.name;ui.meta.textContent=`${copy[lang].pages(pageCount)} · ${formatBytes(file.size)}`;ui.drop.hidden=true;ui.selected.hidden=false;ui.divider.hidden=false;ui.settings.hidden=false;ui.split.disabled=false}catch(error){file=null;pageCount=0;showError(copy[lang].invalidPdf)}}
function parseRange(value){const pages=[];for(const part of value.split(",").map(v=>v.trim()).filter(Boolean)){if(/^\d+$/.test(part)){pages.push(Number(part))}else{const match=part.match(/^(\d+)\s*-\s*(\d+)$/);if(!match)return null;const start=Number(match[1]),end=Number(match[2]);if(start>end)return null;for(let n=start;n<=end;n++)pages.push(n)}}const unique=[...new Set(pages)];return unique.length&&unique.every(n=>n>=1&&n<=pageCount)?unique:null}
async function splitAll(source){const zip=new JSZip();for(let index=0;index<pageCount;index++){const output=await PDFLib.PDFDocument.create(),[page]=await output.copyPages(source,[index]);output.addPage(page);zip.file(`page-${String(index+1).padStart(3,"0")}.pdf`,await output.save())}return{blob:await zip.generateAsync({type:"blob"}),name:"split-pages.zip",kind:"zip"}}
async function extractRange(source){const pages=parseRange(ui.range.value);if(!pages)throw new Error("range");const output=await PDFLib.PDFDocument.create(),copied=await output.copyPages(source,pages.map(n=>n-1));copied.forEach(page=>output.addPage(page));return{blob:new Blob([await output.save()],{type:"application/pdf"}),name:"extracted-pages.pdf",kind:"pdf"}}
ui.drop.addEventListener("click",()=>ui.input.click());ui.replace.addEventListener("click",()=>ui.input.click());ui.input.addEventListener("change",()=>{setFile(ui.input.files[0]);ui.input.value=""});["dragenter","dragover"].forEach(event=>ui.drop.addEventListener(event,e=>{e.preventDefault();ui.drop.classList.add("dragging")}));["dragleave","drop"].forEach(event=>ui.drop.addEventListener(event,e=>{e.preventDefault();ui.drop.classList.remove("dragging")}));ui.drop.addEventListener("drop",e=>setFile(e.dataTransfer.files[0]));
document.querySelectorAll('input[name="method"]').forEach(input=>input.addEventListener("change",()=>{clearResult();ui.rangeField.hidden=method()!=="range"}));ui.range.addEventListener("input",clearResult);
ui.split.addEventListener("click",async()=>{if(!file)return;clearResult();ui.split.disabled=true;ui.status.textContent=copy[lang].processing;try{const source=await PDFLib.PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true}),result=method()==="all"?await splitAll(source):await extractRange(source);resultKind=result.kind;resultSize=result.blob.size;resultUrl=URL.createObjectURL(result.blob);ui.download.href=resultUrl;ui.download.download=result.name;ui.downloadLabel.textContent=result.kind==="zip"?copy[lang].downloadZip:copy[lang].downloadPdf;ui.download.hidden=false;ui.status.textContent=`${result.kind==="zip"?copy[lang].readyZip:copy[lang].readyPdf} · ${formatBytes(result.blob.size)}`;ui.status.className="status success";ui.split.classList.add("completed")}catch(error){showError(error.message==="range"?copy[lang].invalidRange:copy[lang].failed)}finally{ui.split.disabled=!file}});
ui.language.addEventListener("change",()=>{lang=ui.language.value;try{localStorage.setItem("convertfiles24-language",lang)}catch(_){}const url=new URL(location.href);url.searchParams.set("lang",lang);history.replaceState(null,"",url);renderLanguage()});ui.theme.addEventListener("click",()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;try{localStorage.setItem("convertfiles24-theme",next)}catch(_){}renderTheme()});renderTheme();renderLanguage();
})();
