const $ = (s) => document.querySelector(s);
const fileInput = $('#fileInput');
const dropZone = $('#dropZone');
const summary = $('#summary');
const fileList = $('#fileList');
const convertButton = $('#convertButton');
const downloadButton = $('#downloadButton');
const status = $('#status');
let files = [];
let resultUrl = '';

const copy = {
  en:{allTools:'All tools',privacy:'Privacy',eyebrow:'Image tools',title:'JPG / PNG to PDF',subtitle:'Combine several images into one PDF in your chosen order.',caption:'Arrange images · create one PDF',selectLabel:'Select images',dropTitle:'Choose JPG or PNG images',dropCopy:'Select images or drag them here',choose:'Choose images',limit:'Up to 50 images · 25MB each',add:'Add images',localTitle:'Processed on your device',localCopy:'Images are never uploaded to a server.',convert:'Create PDF',download:'Download PDF',why:'Why ConvertFiles24',featureTitle:'Simple image to PDF conversion',privateTitle:'Private by design',privateCopy:'Images stay on your device.',orderTitle:'Your page order',orderCopy:'Move images before creating the PDF.',fitTitle:'Automatic page fit',fitCopy:'Each page matches its image.',copyright:'© 2026 ConvertFiles24. Safe local file tools.',privacyPolicy:'Privacy Policy',terms:'Terms',selected:n=>`${n} image${n===1?'':'s'} selected`,ready:(n,s)=>`PDF ready · ${n} page${n===1?'':'s'} · ${s}`,working:'Creating PDF…',bad:'Only JPG and PNG images are supported.',large:'Each image must be 25MB or smaller.',max:'You can select up to 50 images.',failed:'Could not create the PDF. Please try another image.'},
  ko:{allTools:'모든 도구',privacy:'개인정보 보호',eyebrow:'이미지 도구',title:'JPG / PNG를 PDF로',subtitle:'여러 이미지를 원하는 순서대로 하나의 PDF로 만드세요.',caption:'순서 정리 · 하나의 PDF 만들기',selectLabel:'이미지 선택',dropTitle:'JPG 또는 PNG 이미지를 선택하세요',dropCopy:'이미지를 선택하거나 이곳에 끌어놓으세요',choose:'이미지 선택',limit:'최대 50개 · 파일당 25MB',add:'이미지 추가',localTitle:'기기에서 안전하게 처리',localCopy:'이미지는 서버로 업로드되지 않습니다.',convert:'PDF 만들기',download:'PDF 다운로드',why:'CONVERTFILES24를 선택하는 이유',featureTitle:'간단한 이미지 PDF 변환',privateTitle:'개인정보 보호 설계',privateCopy:'이미지는 사용자의 기기에만 남습니다.',orderTitle:'원하는 페이지 순서',orderCopy:'PDF를 만들기 전에 이미지 순서를 바꿀 수 있습니다.',fitTitle:'자동 페이지 맞춤',fitCopy:'각 페이지가 이미지 크기에 맞춰집니다.',copyright:'© 2026 ConvertFiles24. 안전한 기기 내 파일 처리.',privacyPolicy:'개인정보처리방침',terms:'이용약관',selected:n=>`이미지 ${n}개 선택`,ready:(n,s)=>`PDF가 준비되었습니다 · ${n}페이지 · ${s}`,working:'PDF를 만드는 중…',bad:'JPG와 PNG 이미지만 사용할 수 있습니다.',large:'이미지는 각각 25MB 이하여야 합니다.',max:'이미지는 최대 50개까지 선택할 수 있습니다.',failed:'PDF를 만들지 못했습니다. 다른 이미지로 다시 시도하세요.'},
  ja:{allTools:'すべてのツール',privacy:'プライバシー',eyebrow:'画像ツール',title:'JPG / PNGをPDFへ',subtitle:'複数の画像を好きな順番で1つのPDFにまとめます。',caption:'画像を並べ替え · PDFを作成',selectLabel:'画像を選択',dropTitle:'JPGまたはPNG画像を選択',dropCopy:'画像を選択するか、ここにドラッグしてください',choose:'画像を選択',limit:'最大50枚 · 1枚25MBまで',add:'画像を追加',localTitle:'端末内で安全に処理',localCopy:'画像はサーバーにアップロードされません。',convert:'PDFを作成',download:'PDFをダウンロード',why:'ConvertFiles24を選ぶ理由',featureTitle:'シンプルな画像PDF変換',privateTitle:'プライバシー設計',privateCopy:'画像は端末内に留まります。',orderTitle:'ページ順を変更',orderCopy:'作成前に画像順を変更できます。',fitTitle:'自動ページ調整',fitCopy:'各ページを画像サイズに合わせます。',copyright:'© 2026 ConvertFiles24.',privacyPolicy:'プライバシーポリシー',terms:'利用規約',selected:n=>`${n}枚の画像を選択`,ready:(n,s)=>`PDF準備完了 · ${n}ページ · ${s}`,working:'PDFを作成中…',bad:'JPGとPNG画像のみ対応しています。',large:'各画像は25MB以下にしてください。',max:'画像は最大50枚です。',failed:'PDFを作成できませんでした。'},
  es:{allTools:'Todas las herramientas',privacy:'Privacidad',eyebrow:'Herramientas de imagen',title:'JPG / PNG a PDF',subtitle:'Combina varias imágenes en un PDF en el orden que elijas.',caption:'Ordena imágenes · crea un PDF',selectLabel:'Seleccionar imágenes',dropTitle:'Elige imágenes JPG o PNG',dropCopy:'Selecciona o arrastra imágenes aquí',choose:'Elegir imágenes',limit:'Hasta 50 imágenes · 25MB cada una',add:'Añadir imágenes',localTitle:'Procesado en tu dispositivo',localCopy:'Las imágenes no se suben al servidor.',convert:'Crear PDF',download:'Descargar PDF',why:'Por qué elegir ConvertFiles24',featureTitle:'Conversión sencilla a PDF',privateTitle:'Privacidad por diseño',privateCopy:'Las imágenes permanecen en tu dispositivo.',orderTitle:'Tu orden de páginas',orderCopy:'Ordena las imágenes antes de crear el PDF.',fitTitle:'Ajuste automático',fitCopy:'Cada página se adapta a su imagen.',copyright:'© 2026 ConvertFiles24.',privacyPolicy:'Política de privacidad',terms:'Términos',selected:n=>`${n} imágenes seleccionadas`,ready:(n,s)=>`PDF listo · ${n} páginas · ${s}`,working:'Creando PDF…',bad:'Solo se admiten imágenes JPG y PNG.',large:'Cada imagen debe pesar 25MB o menos.',max:'Puedes elegir hasta 50 imágenes.',failed:'No se pudo crear el PDF.'}
};

let lang = new URLSearchParams(location.search).get('lang') || localStorage.getItem('convertfiles24-lang') || 'en';
if(!copy[lang]) lang='en';
const t=()=>copy[lang];
function applyLanguage(){document.documentElement.lang=lang; $('#languageSelect').value=lang; document.querySelectorAll('[data-i18n]').forEach(el=>{const v=t()[el.dataset.i18n]; if(typeof v==='string') el.textContent=v;}); render();}
function bytes(n){if(n<1024)return `${n} B`; if(n<1048576)return `${(n/1024).toFixed(1)} KB`; return `${(n/1048576).toFixed(1)} MB`;}
function clearResult(){if(resultUrl) URL.revokeObjectURL(resultUrl); resultUrl=''; downloadButton.hidden=true; status.textContent='';}
function render(){const has=files.length>0; dropZone.hidden=has; summary.hidden=!has; fileList.hidden=!has; convertButton.disabled=!has; if(!has)return; $('#count').textContent=t().selected(files.length); $('#total').textContent=bytes(files.reduce((a,f)=>a+f.size,0)); fileList.innerHTML=''; files.forEach((f,i)=>{const row=document.createElement('div'); row.className='file-row'; row.innerHTML=`<div><strong></strong><small>${i+1} · ${bytes(f.size)}</small></div><div class="file-actions"><button aria-label="Move up">↑</button><button aria-label="Move down">↓</button><button aria-label="Remove">×</button></div>`; row.querySelector('strong').textContent=f.name; const buttons=row.querySelectorAll('button'); buttons[0].disabled=i===0; buttons[1].disabled=i===files.length-1; buttons[0].onclick=()=>move(i,-1); buttons[1].onclick=()=>move(i,1); buttons[2].onclick=()=>{files.splice(i,1);clearResult();render();}; fileList.append(row);});}
function move(i,d){const j=i+d; [files[i],files[j]]=[files[j],files[i]]; clearResult();render();}
function addFiles(list){const incoming=[...list]; if(files.length+incoming.length>50){status.textContent=t().max;return;} if(incoming.some(f=>!['image/jpeg','image/png'].includes(f.type))){status.textContent=t().bad;return;} if(incoming.some(f=>f.size>25*1024*1024)){status.textContent=t().large;return;} files.push(...incoming);clearResult();render();}
dropZone.onclick=()=>fileInput.click(); $('#addButton').onclick=()=>fileInput.click(); fileInput.onchange=()=>{addFiles(fileInput.files);fileInput.value='';};
['dragenter','dragover'].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.add('dragging');})); ['dragleave','drop'].forEach(e=>dropZone.addEventListener(e,x=>{x.preventDefault();dropZone.classList.remove('dragging');})); dropZone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
function readBuffer(file){return file.arrayBuffer();}
convertButton.onclick=async()=>{clearResult();convertButton.disabled=true;status.textContent=t().working;try{const doc=await PDFLib.PDFDocument.create();for(const file of files){const data=await readBuffer(file);const image=file.type==='image/png'?await doc.embedPng(data):await doc.embedJpg(data);const page=doc.addPage([image.width,image.height]);page.drawImage(image,{x:0,y:0,width:image.width,height:image.height});}const out=await doc.save();const blob=new Blob([out],{type:'application/pdf'});resultUrl=URL.createObjectURL(blob);downloadButton.href=resultUrl;downloadButton.download='images.pdf';downloadButton.hidden=false;status.textContent=t().ready(files.length,bytes(blob.size));}catch(e){console.error(e);status.textContent=t().failed;}finally{convertButton.disabled=!files.length;}};
$('#languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('convertfiles24-lang',lang);const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState({},'',u);applyLanguage();};
$('#themeButton').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('convertfiles24-theme',next);$('#themeIcon').textContent=next==='dark'?'☾':'☀';};
$('#themeIcon').textContent=document.documentElement.dataset.theme==='dark'?'☾':'☀'; applyLanguage();
